zuul.ignored-services: "*"
zuul.prefix: /api
zuul.routes.customerservice: /customers/**
zuul.routes.orderservice: /orders/**
zuul.debug.request: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2500